//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterAuthority
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RoleModules
    {
        public int Id { get; set; }
        public string ModulesName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Path { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string RoleName { get; set; }
        public int Weight { get; set; }
    }
}
